<a href="https://colab.research.google.com/github/shereenm88/Data-Analysis-NanoDegree/blob/main/Hugging_Face_Speech_to_Text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

In [2]:
from transformers import pipeline

In [ ]:
import transformers
print(transformers.__version__)

In [5]:
!pip install ipython

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 22.6 MB/s eta 0:00:00


In [8]:
!pip install transformers

In [10]:
import librosa #extract audo features from audio files and it can manipulate audio files in a variety of formats such as wav, MP3
import torch #libraru used for applications such as computer vision and NLP
import IPython.display as display #interactive command line for Python
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np #metricies, arrays and so on


In [12]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You sho

In [14]:
audio, sampling_rate = librosa.load('/quothello-therequot-158832.mp3', sr = 16000)


In [15]:
audio, sampling_rate

(array([-3.1075795e-24,  1.5527254e-24, -5.2678388e-24, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00], dtype=float32),
 16000)

In [16]:
display.Audio('/quothello-therequot-158832.mp3', autoplay=True)

In [17]:
input_values = tokenizer(audio, return_tensors="pt").input_values
input_values

tensor([[0.0014, 0.0014, 0.0014,  ..., 0.0014, 0.0014, 0.0014]])

In [19]:
logits = model(input_values).logits
logits

tensor([[[ 13.3522, -26.4937, -26.2292,  ...,  -5.8062,  -6.5638,  -5.7964],
         [ 13.3612, -26.5225, -26.2542,  ...,  -5.8371,  -6.5616,  -5.8145],
         [ 13.3942, -26.5694, -26.3001,  ...,  -5.8596,  -6.5858,  -5.8324],
         ...,
         [ 13.5660, -26.6483, -26.3816,  ...,  -5.8484,  -6.9503,  -5.6261],
         [ 13.4914, -26.6371, -26.3752,  ...,  -5.8783,  -6.9969,  -5.6359],
         [ 13.3561, -26.5382, -26.2803,  ...,  -5.8875,  -6.9998,  -5.6557]]],
       grad_fn=<ViewBackward0>)

In [20]:
#We will store predicted IDs then we will pass the logists to values to soft max to get the predicted value
Predicted_ids = torch.argmax(logits, dim=-1)
Predicted_ids

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 11,  0,  7, 15,  0, 15,
         15,  0,  8,  0,  0,  0,  4,  0,  6, 11,  0,  0,  0,  5,  0, 13,  0,  4,
          4,  4,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [21]:
transcriptions = tokenizer.decode(Predicted_ids[0])
transcriptions

'HALLO THER'